version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "6306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vbhuvZ82aruEchec
      MYSQL_DATABASE: nexus
  redis:
    image: redis:latest
  nexus-app:
    image: tuantranf/php-71-image
    container_name: nexus-app
    volumes:
      - "..:/var/www/html"
      - "./data:/var/run/httpd/"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    environment:
      APP_NAME: "Nexus"
      MYSQL_ROOT_PASSWORD: vbhuvZ82aruEchec
      MYSQL_DATABASE:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:1T99e3tXq0GbpGx2ht8IV56zWlA7wQuG0+pHy7f9CFU=
      DB_HOST: mysql
      DB_DATABASE: nexus
      DB_USERNAME: root
      DB_PASSWORD: vbhuvZ82aruEchec
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: sync
      REDIS_HOST: redis
    ports:
      - "80:80"
    tty: true
